### ISSUE TITLE
KWS FP32 model is not FP32

### ISSUE THREAD

**Issue by colbybanbury** [eembc/ulpmark-ml#13]
The FP32 KWS model in [base_models](https://github.com/eembc/benchmark-runner-ml/tree/main/base_models/kws01) is actually a copy of the Int8 model.

Both models have the same hash (618aeb155673dae92fa6a7f26608add5) and if you open the fp32 model in Netron you can see the weights are fp32.

**Comment by petertorelli** [comment]
Thanks for catching this. Since both organizations mandate starting from fp32 TFLite models, I have removed all int8 to avoid confusion.

**Comment by petertorelli** [comment]
Re-opening because the MLC tiny model is int8. Colby, please add the real fp32 model to the tiny repo and i'll copy it here.

**Comment by honson1** [comment]
@colbybanbury Touching base on this before Thursday to see when the kws fp32 model will be posted!

**Comment by petertorelli** [comment]
@colbybanbury Ping?

**Comment by colbybanbury** [comment]
The float model has been uploaded to the TinyMLPerf repo: [link](https://github.com/mlcommons/tiny/blob/master/v0.1/training/keyword_spotting/trained_models/kws_ref_model_float32.tflite)

No MD5 yet but I can add that.

@honson1 is this considered resolved then?

**Comment by petertorelli** [comment]
@colbybanbury Thanks! I just made a copy.
