### ISSUE TITLE
GUI partially renders on Ubuntu 18.04 under Parallels virtual machine on macOS

### ISSUE THREAD

**Issue by petertorelli** [eembc/ulpmark-ml#14]
Javier from FermiLabs demonstrated the Linux GUI not displaying any text (blank white window), or displaying a 1/4 white rectangle in the upper right corner with 3/4 black window, when launching the runner on macOS + parallels VM + Ubuntu 18.04 + gnome.

**Comment by jmduarte** [comment]
@petertorelli I've been able to "solve" the issue by uninstalling "Parallels Tools" (https://kb.parallels.com/117044), which does some graphics things under the hood (like automatically resizing the screen, etc).

**Comment by petertorelli** [comment]
@jmduarte Great, thanks for letting me know!
